### ISSUE TITLE
Add product IT to ensure Headless Admin App loading

### ISSUE THREAD

**Issue by AShroti** [adobe/aem-test-samples#41]
### Expected Behaviour

We have experienced on multiple occasions that custom project code has overridden CORS/CSRF/Sling Filter configs that conflicts with the respective OOTB AEM configurations. Duet to which following APIs request gets blocked:

POST/libs/dam/cfm/headless/endpoints/content/graphql.json
POST/libs/dam/cfm/headless/endpoints/content/graphql.A.json

For e.g. WKND Site [has overridden these configs](https://github.com/adobe/aem-guides-wknd/tree/master/ui.config/src/main/content/jcr_root/apps/wknd/osgiconfig/config.author). Created an [issue#301](https://github.com/adobe/aem-guides-wknd/issues/301)

As part of this issue, we should add the Product Functional tests to ensure:
A. the backend headless APIs (GraphQL) should not break due to custom configurations.
B. Headless Admin App is getting loaded with a repo pointing to the AEM CS author environment **through IMS user**

**NOTE**: The backend headless APIs (GraphQL) is supported under specific FT. Ensure the feature is enabled before running the tests.

**Comment by dulvac** [comment]
Closing this as it's very old. This is a samples repository, it is not meant to provide full testing coverage for AEM.
