### ISSUE TITLE
I have been trying to use Selenium-Webdriver in my project for 2 weeks without any luck.

### ISSUE THREAD

**Issue by kenny-q** [adobe/aem-test-samples#70]
### Expected Behaviour
Documentation written in a way everyone could follow and understand it.
### Actual Behaviour
I've been trying to follow the documentation to integrate Selenium Webdriver into my project generated with a Maven archetype on a AEMaaCS environment and I can say that it's hardly impossible to follow the documentation and make it works.
#### Steps to Reproduce
1- Create a new AEM local instance using AEMaaCS latest SDK from Software Distribution
2- Generate your sourcecode using Maven archetype 41
3- Trying to modify the ui.test module on your project and use the Selenium-Webdriver from aem-test-samples repo FOLLOWING the README and make it works.

**Comment by volteanu** [comment]
@kenny-q, would you mind adding more details about the problem? You can follow the issue template and fill in the sections for sample code and logs or go with more free form to describe in more details the issue you encountered.

**Comment by kenny-q** [comment]
I did it on the steps to reproduce. I will expect that the README is written to be followed, well it is not.

**Comment by bisswanger** [comment]
@kenny-q 
When we released cypress test module, we created a small documentation in the readme on adding it to Cloud Manager

Can you check on these steps, they are rather simple:
https://github.com/adobe/aem-test-samples/tree/aem-cloud/ui-cypress#integrate-into-your-cloud-manager-repository

**Comment by kenny-q** [comment]
But I was more interested in the Selenium Webdriver, been trying to integrate it on my project for two weeks already without luck. I think I'll try the Cypress to figure it out what's missing for Selenium-Webdriver sample.

**Comment by bisswanger** [comment]
@kenny-q 
No, the steps for adding Selenium WebDriver are exactly the same as in that chapter.
Just using the files from the selenium folder instead

**Comment by kenny-q** [comment]
On a AEM project by default I can run the tests with `mvn clean verify -Pui-tests-local-execution` without having any problems.
When I change that module with the files on the Selenium-Webdriver module I cannot run the tests, I've tried replacing just the **test-module** folder, or everything inside **ui.tests** with the files inside on **ui-selenium-webdriver** and then modifying the pom.xml to match my project and every time I ran the maven command again I'm getting this:

![image](https://github.com/adobe/aem-test-samples/assets/74611132/0773ac3e-7f78-41cc-8fb5-a7b20e159967)

And that profile did exists on the pom, so something is not right, or I'm missing something from the documentation.

**Comment by bisswanger** [comment]
hm, the log looks like you are running the `mvn clean verify` command in the root folder.
The commands in the README are supposed to be executed in the same folder where the readme is located if not stated otherwise.

i.e. you need to run it inside the `ui.tests` folder

**Comment by bisswanger** [comment]
This will run a full Docker based test execution.
You may also check the public AEM documentation on running the tests "locally": https://experienceleague.adobe.com/docs/experience-manager-cloud-service/content/implementing/using-cloud-manager/test-results/functional-testing/ui-testing.html?lang=en#java-sample

**Comment by kenny-q** [comment]
I see, but should I suppose to have docker installed as well? I'm not seeing any mention to that.

![image](https://github.com/adobe/aem-test-samples/assets/74611132/63388198-a232-403c-b6d3-1a8d52a7cd90)

**Comment by kenny-q** [comment]
Not to mention that is still not clear to me, if I need to replace my whole default **ui.test** with **ui-selenium-webdriver** and everything on it or just replace the **test-module** inside of it.
In the case I need to replace everything I'm seeing 2 pom.xml, one at the root of ui-selenium-webdriver and another inside test-module. So, what should I modify on them?
Docker? What's going on with the docker? What do I need to do?

From my experience that's my main problem, I can generate a new archetype project, run **mvn clean verify -Pui-tests-local-execution** and everything is brilliant.
When I try to use this very simple sample for Selenium-Webdriver, everything is chaos, maybe for a more experience person this is very intuitive, but not in my case. And the idea to create README and documentation is that EVERYONE could follow in a very simple way. 

I don't know if I make myself clear because I'm really frustrated at this point on using Selenium on my project. Thanks anyways for the help.

**Comment by bisswanger** [comment]
You basically have 2 options:
* Either install docker and then run this command
* Or else run selenium server on your machine. (https://www.selenium.dev/downloads/)

The documentation refers to the Docker version as that's the fastest way to set it up.
(the verification on AEM also will use these images)

I would assume that stating a docker command in instructions should be clear enough for technical users to understand that docker installation is needed ;-)

**Comment by bisswanger** [comment]
Thanks for the notes. I will have a look at the documentation and what we can improve there.
Your feedback is indeed very helpful to improve here :-)

**Comment by bisswanger** [comment]
> Not to mention that is still not clear to me, if I need to replace my whole default ui.test with ui-selenium-webdriver and everything on it or just replace the test-module inside of it.

You should replace everything there

> In the case I need to replace everything I'm seeing 2 pom.xml, one at the root of ui-selenium-webdriver and another inside test-module. So, what should I modify on them?

Technically you can keep the pom.xml files as they are, that shall work.
You could modify the one directly in `ui.tests` folder to reflect the proper parent / version.

The on inside the `test-module` folder could be adjusted but only on naming.
i.e. do not add any parent relationship there, else the execution later may fail as the parent is not inside the generated docker image

> Docker? What's going on with the docker? What do I need to do?

if you don't have docker, what you can do:
- download selenium server JAR
- start selenium JAR locally, e.g. on port 4444
- then you can call the verify inside the `test-module` folder

For running the docker build + verification in the root folder, you indeed would need docker.
Without, it won't work

> From my experience that's my main problem, I can generate a new archetype project, run mvn clean verify -Pui-tests-local-execution and everything is brilliant.

True, I agree on this.
WDIO (and also the Cypress example) are more flexible as they will download all required resources and start processes in the background.
Unfortunately, for Java based Selenium, things are a bit more complicated as there is no "single library" approach there

**Comment by kenny-q** [comment]
Thanks for clarifying all the points, it has been VERY helpful. I will try again a new project from scratch knowing all this now.
