### ISSUE TITLE
ui-selenium-webdriver: Maven profile "ui-tests-local-execution" does not exist

### ISSUE THREAD

**Issue by kwin** [adobe/aem-test-samples#91]
Although the README in https://github.com/adobe/aem-test-samples/tree/aem-cloud/ui-selenium-webdriver#locally-standalone mentions a Maven profile named `ui-tests-local-execution`, this is not defined in the effective POM. Therefore the local execution does not work as described.

**Comment by bisswanger** [comment]
Hi @kwin,

thanks for your issue.
Though I think we should be fine here

https://github.com/adobe/aem-test-samples/blob/aem-cloud/ui-selenium-webdriver/README.md?plain=1#L44

```
Change to test-module directory
```

The `pom.xml` inside that folder contains the mentioned profile:
https://github.com/adobe/aem-test-samples/blob/aem-cloud/ui-selenium-webdriver/test-module/pom.xml#L102

**Comment by kwin** [comment]
Indeed, sorry haven't paid enough attention while reading.
